name: app_port_cap
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.5 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.4.1
  get: ^4.6.5
  get_storage: ^2.0.3
  cloud_firestore: ^4.3.1
  firebase_analytics: ^10.1.0
  firebase_crashlytics: ^3.0.9
  firebase_database: ^10.0.9
  firebase_app_check: ^0.1.1+8
  firebase_messaging: ^14.2.1
  flutterfire_cli: ^0.2.7
  firebase_auth: ^4.2.4

  flutterfire: ^0.0.1
  simple_animations: ^3.2.0
  lottie: ^2.1.0
  fluttertoast: ^8.1.2
  package_info_plus: ^3.0.2
  icons_plus: ^3.0.0
  device_info_plus: ^8.0.0
  android_id: ^0.1.3+1

  colorize_text_avatar: ^1.0.2
  cached_network_image: ^3.2.3
  random_avatar: ^0.0.7
  tiny_avatar: ^0.0.3
  flutter_map: ^3.1.0
  location: ^4.4.0
  json_theme: ^4.0.3+2
  provider: ^6.0.5
  flutter_local_notifications: ^13.0.0
  timezone: ^0.9.1
  permission_handler: ^10.2.0
  google_fonts: ^3.0.1
  flame_splash_screen: ^0.1.0
  graphview: ^1.1.1
  dropdown_button2: ^1.9.2
  connectivity_wrapper: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.1.0
  icons_launcher: ^2.0.6

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/images/
    - assets/images/avatars/
    - assets/themes/appainter_theme.json

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins-Italic.ttf
          style: italic
        - asset: fonts/Poppins-Medium.ttf
          weight: 500

icons_launcher:
  image_path: "assets/icon/play_store_512.png"
  platforms:
    android:
      enable: true
      image_path: "assets/icon/play_store_512.png"
      adaptive_background_image: "assets/icon/ic_launcher_background.png"
      adaptive_foreground_image: "assets/icon/ic_launcher_foreground.png"
      adaptive_round_image: "assets/icon/ic_launcher.png"
    ios:
      enable: true
      image_path: "assets/icon/play_store_512.png"
    web:
      enable: true
      image_path: "assets/icon/play_store_512.png"
      favicon_path: "assets/icon/play_store_512.png"
