// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmJRoicVoIuHM46FbZ3yYbv6Yy63-D3NA',
    appId: '1:649507476750:web:165f891d6b99e1e24a335f',
    messagingSenderId: '649507476750',
    projectId: 'port-capacity',
    authDomain: 'port-capacity.firebaseapp.com',
    databaseURL: 'https://port-capacity-default-rtdb.firebaseio.com',
    storageBucket: 'port-capacity.appspot.com',
    measurementId: 'G-2D7EYFREXE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwAMlisKWrUck89e4be7ExHlbqsxWqMcw',
    appId: '1:649507476750:android:3533b4111d9dc2064a335f',
    messagingSenderId: '649507476750',
    projectId: 'port-capacity',
    databaseURL: 'https://port-capacity-default-rtdb.firebaseio.com',
    storageBucket: 'port-capacity.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_AS7cnX0GhOxgPmRgvdwcDG5-HIR8njk',
    appId: '1:649507476750:ios:bce6875800435a664a335f',
    messagingSenderId: '649507476750',
    projectId: 'port-capacity',
    databaseURL: 'https://port-capacity-default-rtdb.firebaseio.com',
    storageBucket: 'port-capacity.appspot.com',
    iosClientId: '649507476750-s1fs4ov2t9plgj16s4uphkvhkv9hlbpa.apps.googleusercontent.com',
    iosBundleId: 'com.example.appPortCap',
  );
}
